# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:anby_demara/animations/walk_loop/pause
function animated_java:anby_demara/animations/run_loop/pause
function animated_java:anby_demara/animations/dash_exit/pause