# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.anby_demara.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'anby_demara', 'function_path': 'animated_java:anby_demara/variants/default/apply'}
execute on passengers if entity @s[tag=aj.anby_demara.bone.head] run function animated_java:anby_demara/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.anby_demara.bone.leftarmtop] run function animated_java:anby_demara/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.anby_demara.bone.leftarmbottom] run function animated_java:anby_demara/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.anby_demara.bone.rightarmtop] run function animated_java:anby_demara/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.anby_demara.bone.weapon] run function animated_java:anby_demara/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.anby_demara.bone.rightarmhand] run function animated_java:anby_demara/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.anby_demara.bone.weaponcase] run function animated_java:anby_demara/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.anby_demara.bone.backpack] run function animated_java:anby_demara/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.anby_demara.bone.thorax] run function animated_java:anby_demara/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.anby_demara.bone.leftlegtop] run function animated_java:anby_demara/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.anby_demara.bone.leftlegbottom] run function animated_java:anby_demara/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.anby_demara.bone.rightlegtop] run function animated_java:anby_demara/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.anby_demara.bone.rightlegbottom] run function animated_java:anby_demara/variants/default/zzz/12