# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.anby_demara.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'anby_demara', 'function_path': 'animated_java:anby_demara/animations/walk_entry/stop'}
tag @s remove aj.anby_demara.animation.walk_entry.playing
scoreboard players set @s aj.walk_entry.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:anby_demara/animations/walk_entry/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only