# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:anby_demara/animations/idle_loop/zzz/apply_frame {frame: 1}
scoreboard players add @s aj.idle_loop.frame 1