# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.anby_demara.root] run return 0
execute on passengers if entity @s[tag=aj.anby_demara.data] unless data entity @s {data:{rigHash: 'b0ae8cb06cbf517e83a45281a9f6d6ee789ac204ed106cda46b65a6b5878ff7a'}} on vehicle run function animated_java:anby_demara/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1