# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.anby_demara.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:anby_demara/as_root/pre_tick
execute if entity @s[tag=aj.anby_demara.animation.idle_loop.playing] run function animated_java:anby_demara/animations/idle_loop/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.walk_entry.playing] run function animated_java:anby_demara/animations/walk_entry/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.walk_loop.playing] run function animated_java:anby_demara/animations/walk_loop/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.walk_exit.playing] run function animated_java:anby_demara/animations/walk_exit/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.run_loop.playing] run function animated_java:anby_demara/animations/run_loop/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.dash_forward.playing] run function animated_java:anby_demara/animations/dash_forward/zzz/on_tick
execute if entity @s[tag=aj.anby_demara.animation.dash_exit.playing] run function animated_java:anby_demara/animations/dash_exit/zzz/on_tick
execute on passengers if entity @s[tag=aj.anby_demara.data] run function animated_java:anby_demara/root/zzz/1
#execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:anby_demara/as_root/post_tick