# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:anby_demara/animations/walk_loop/zzz/apply_frame {frame: 12}
scoreboard players add @s aj.walk_loop.frame 1