# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle_loop.frame dummy
scoreboard objectives add aj.walk_entry.frame dummy
scoreboard objectives add aj.walk_loop.frame dummy
scoreboard objectives add aj.walk_exit.frame dummy
scoreboard objectives add aj.run_loop.frame dummy
scoreboard objectives add aj.dash_forward.frame dummy
scoreboard objectives add aj.dash_exit.frame dummy
execute as @e[type=item_display,tag=aj.anby_demara.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:anby_demara/root/on_load