# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.anby_demara.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'anby_demara', 'function_path': 'animated_java:anby_demara/animations/dash_forward/next_frame'}
execute if score @s aj.dash_forward.frame matches 4.. run scoreboard players set @s aj.dash_forward.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.dash_forward.frame
execute at @s run function animated_java:anby_demara/animations/dash_forward/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.dash_forward.frame 1