# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.anby_demara.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'anby_demara', 'function_path': 'animated_java:anby_demara/animations/walk_exit/next_frame'}
execute if score @s aj.walk_exit.frame matches 17.. run scoreboard players set @s aj.walk_exit.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.walk_exit.frame
execute at @s run function animated_java:anby_demara/animations/walk_exit/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.walk_exit.frame 1