# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:anby_demara/animations/run_loop/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.run_loop.frame 1