# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.leftarmtop] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarmtop set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.leftarmbottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarmbottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.rightarmtop] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarmtop set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.weapon] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weapon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.rightarmhand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarmhand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.weaponcase] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weaponcase set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.backpack] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_backpack set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.thorax] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_thorax set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.leftlegtop] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftlegtop set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.leftlegbottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftlegbottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.rightlegtop] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightlegtop set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.anby_demara.bone.rightlegbottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightlegbottom set from storage aj:uuid main.out